name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"     # roda diariamente à meia-noite
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake SVG
        uses: Platane/snk@v3
        id: snake
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Deploy SVG to branch
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git clone --branch output https://github.com/${{ github.repository }} output || git clone https://github.com/${{ github.repository }} output
          cd output
          cp -r ../dist/* .
          git add .
          git commit -m "Update snake animation" || echo "No changes to commit"
          git push origin output --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

