name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"     # roda diariamente à meia-noite
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake SVG
        uses: Platane/snk@v3
        id: snake
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg

            - name: Deploy SVG to branch
        run: |
          set -eux  # ativa modo de debug para mostrar comandos e sair em erro
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

          # Tenta clonar branch 'output', se falhar clona todo repositório e cria branch 'output'
          if git clone --branch output https://github.com/${{ github.repository }} output; then
            echo "Branch 'output' clonada com sucesso"
            cd output
          else
            echo "Branch 'output' não existe, criando branch"
            git clone https://github.com/${{ github.repository }} output
            cd output
            git checkout -b output
          fi

          cp -r ../dist/* .
          git add .
          git commit -m "Update snake animation" || echo "Sem alterações para commitar"
          git push origin output --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


